services:
  redis-in-go:
    build: .
    image: redis-in-go:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/app
    restart: unless-stopped
  bench:
    image: redis:7-alpine
    depends_on:
      - redis-in-go
    entrypoint: ["redis-benchmark"]
